- name: Configure Web Access Node
  hosts: web
  remote_user: root
  gather_facts: True
  roles:
    - flightwebminimal
    - openflight.generic.flightenv
    - openflight.generic.flightweb
    - openflight.generic.user
